### PR TITLE
Make window frameless, update tray info

### PR DESCRIPTION
**Pull request by AyymericM**
• Added a tray icon and tray menu to restore the app when "closed"
• Polished the design with a frame less window and some stylised control buttons
• Removed that ugly and useless top menu bar on windows

### CODE REVIEW

**Comment by cassidoo** [comment]
One nitpick thing, the whole project uses 2 spaces instead of 4, mind fixing?

**Comment by farskid** [comment]
The space issue could be solved by adding an `.editorconfig` file to the root directory of project. Would happily add it if needed.

**Comment by AyymericM** [comment]
Yeah you can do it ! I never used a config file for that, I just use beautify on Atom for my indentation :)

**Comment by farskid** [comment]
The thing is, linters and config files help, improve consistency across the team :)

**Comment by cassidoo** [comment]
Going to test this on Windows when I get home and review after that. :)

**Comment by cassidoo** [comment]
image

A few issues on Mac.
Tray icon is super large, plus the X and _ buttons on Mac are usually on left.

If you go for a frameless window, on Windows there still needs to be some way to have a menu.  Open to ideas here.

**Comment by AyymericM** [comment]
All right, will fix theses issues asap !

**Pull request closed without merging**
